import Link from "next/link";
import SiteHeader from "../components/SiteHeader";

export default function AboutPage() {
  return (
    <main className="bg-white text-black min-h-screen">
      <SiteHeader />
      <div className="max-w-6xl mx-auto p-6 md:p-12">
        <h1 className="text-4xl md:text-6xl font-bold mb-8 text-center text-yellow-700">About Tabor Painting</h1>
        <p className="text-lg md:text-xl text-gray-700 max-w-3xl mx-auto text-center mb-10 leading-relaxed">Tabor Painting is a Berlin, Massachusetts painting company providing professional interior painting, exterior painting, and residential painting services throughout Central Massachusetts.</p>
        <div className="space-y-6">
          <section className="bg-white border border-yellow-600/30 rounded-3xl shadow-2xl p-6 md:p-10"><h2 className="text-2xl md:text-3xl font-bold mb-4">Our Story</h2><p className="text-gray-700 leading-relaxed">Tabor Painting was built on hard work, quality craftsmanship, and hands-on painting experience. Founded by Jason Beirne after working with Student Painters, the company was created to provide homeowners in Berlin, Massachusetts and nearby Central MA towns with dependable painting services. Every project is handled with careful prep, clean work, steady communication, and strong attention to detail. Whether the job is interior painting, exterior painting, repainting, trim painting, or a full home refresh, Tabor Painting focuses on a clean, professional, long-lasting result.</p></section>
          <section className="bg-white border border-yellow-600/30 rounded-3xl shadow-2xl p-6 md:p-10"><h2 className="text-2xl md:text-3xl font-bold mb-4">Our Mission</h2><p className="text-gray-700 leading-relaxed">Our mission is to become a trusted choice for homeowners searching for a professional painter in Berlin, MA. Tabor Painting provides high-quality interior and exterior painting with reliable communication, respectful service, and workmanship that is done the right way. From preparation to cleanup, our mission is to make painting your home feel simple, professional, and worth the investment.</p></section>
          <section className="bg-white border border-yellow-600/30 rounded-3xl shadow-2xl p-6 md:p-10"><h2 className="text-2xl md:text-3xl font-bold mb-4">What We Do</h2><p className="text-gray-700 leading-relaxed">Tabor Painting provides residential painting services designed to improve the appearance, comfort, and curb appeal of your home. Our work includes interior painting in Berlin MA, exterior painting in Berlin MA, wall painting, trim painting, door painting, touch-ups, repainting, and detail-focused preparation. We focus on clean lines, smooth finishes, proper surface prep, neat work areas, and a finished result that makes the space feel fresh and well cared for.</p></section>
          <section className="bg-white border border-yellow-600/30 rounded-3xl shadow-2xl p-6 md:p-10"><h2 className="text-2xl md:text-3xl font-bold mb-4">Why Choose Us</h2><p className="text-gray-700 leading-relaxed">Choosing the right painter matters. Tabor Painting focuses on showing up professionally, communicating clearly, protecting the property, and paying attention to the details that make a paint job look finished instead of rushed. Homeowners looking for a reliable painter in Berlin, Massachusetts want clean prep, sharp edges, dependable timelines, and a painting company that takes pride in the work.</p></section>
          <section className="bg-white border border-yellow-600/30 rounded-3xl shadow-2xl p-6 md:p-10"><h2 className="text-2xl md:text-3xl font-bold mb-4">Socials</h2><p className="text-gray-700 leading-relaxed">Social pages can be added here once they are ready.</p></section>
          <section className="bg-white border border-yellow-600/30 rounded-3xl shadow-2xl p-6 md:p-10"><h2 className="text-2xl md:text-3xl font-bold mb-4">Areas We Serve</h2><p className="text-gray-700 leading-relaxed">Tabor Painting is based in Berlin, Massachusetts and serves homeowners in Berlin and nearby Central Massachusetts communities. Common service areas include Berlin, Bolton, Hudson, Clinton, Marlborough, Northborough, Boylston, West Boylston, Sterling, Lancaster, and Worcester. If you are near Berlin MA and need a reliable interior painter, exterior painter, or residential painting company, contact Tabor Painting to see if your project is within our service area.</p></section>
        </div>
        <div className="text-center mt-10"><Link href="/contact" className="bg-black hover:bg-yellow-700 text-white px-8 py-4 rounded-xl font-semibold transition">contact us</Link></div>
      </div>
      <footer className="border-t border-yellow-600/30 py-8 text-center px-4"><p>Taborpainting508@gmail.com</p><p className="mt-1">(774)-245-3383</p><p className="mt-4 text-sm font-semibold text-gray-500">Made and managed by <a href="https://arc-websites.vercel.app" target="_blank" rel="noopener noreferrer" className="text-yellow-700 underline hover:text-black">ARK Websites</a></p><Link href="/privacy" className="inline-block mt-4 text-yellow-700 hover:text-black">Privacy Policy</Link></footer>
    </main>
  );
}
